# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Java CI with Maven
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.7
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file: :
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_PROJECTKEY: ${{ secrets.SONAR_PROJECTKEY }}
        SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar --file ch-covidcertificate-backend-config/pom.xml
    - name: Echo current ref
      run: echo "${{ github.ref }}"
    - name: shasum
      run: shasum -a 256 ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-verifier-ws/target/ch-covidcertificate-backend-config-verifier-ws.jar > ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-verifier-ws/target/ch-covidcertificate-backend-config-verifier-ws.jar.sha256
      shell: bash
    - name: shasum
      run: shasum -a 256 ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/target/ch-covidcertificate-backend-config-wallet-ws.jar > ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/target/ch-covidcertificate-backend-config-wallet-ws.jar.sha256
      shell: bash
    - name: Create Snapshot Release
      uses: ncipollo/release-action@v1
      if: github.ref == 'refs/heads/develop'
      id: create_release
      with:
        name: Snapshot Release ${{ github.ref }}
        tag: SNAPSHOT
        artifacts: "ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-verifier-ws/target/ch-covidcertificate-backend-config-verifier-ws.jar,ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-verifier-ws/target/ch-covidcertificate-backend-config-verifier-ws.jar.sha256,ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/target/ch-covidcertificate-backend-config-wallet-ws.jar,ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/target/ch-covidcertificate-backend-config-wallet-ws.jar.sha256"
        body: |
            Changes in this Release
            - Snapshot release
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        prerelease: false
        allowUpdates: true
